@startuml ShowInvoiceListSequence
actor "Admin" as User
boundary "PrimaryController (B)" as Boundary
control "ShowInvoiceListUseCase (C)" as Control
database "InvoiceDAOGateway" as Gateway
entity "InvoiceDTO" as DTO

User -> Boundary : yêu cầu hiển thị danh sách hóa đơn
activate Boundary
Boundary -> Control : executeForUI()
activate Control
Control -> Gateway : getAll()
activate Gateway
Gateway --> Control : List<InvoiceDTO>
deactivate Gateway
Control -> Control : chuyển đổi List<InvoiceDTO> thành List<InvoiceDisplayData>
Control --> Boundary : List<InvoiceDisplayData>
deactivate Control
Boundary --> User : hiển thị danh sách hóa đơn
deactivate Boundary
@enduml
